#
# This is our properties file
#
#
spring:
  main:
    show_banner: false
#
logging:
  level:
    com:
      walkingfood: DEBUG
#
routes:
  from:
    start: seda:start
  to:
    finish: seda:finish
#