#
# This is our properties file
#
#
spring:
  main:
    show_banner: false
#
logging:
  level:
    com:
      walkingfood: DEBUG
    org:
      apache: WARN
      springframework: WARN
#
routes:
  from:
    start: seda:start
  to:
    finish: seda:finish
#
server:
  port: 8181
#